version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    container_name: dendreth-api-server
    networks:
      - dendreth-network
 
  relayer:
    build:
      context: .
      dockerfile: ./packages/relayer/Dockerfile
    container_name: dendreth-relayer
    networks:
      - dendreth-network

networks:
  dendreth-network:
    driver: bridge

