version: "3.8"
services:

  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - 6379:6379
    networks:
      - net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  rabbitmq: 
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    container_name: dendreth-api-server
    networks:
      - net
    ports:
      - "3002:3002"

  relayer:
    build:
      context: .
      dockerfile: ./packages/relayer/Dockerfile
    container_name: dendreth-relayer
    networks:
      - net
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      server:
        condition: service_started

networks:
  net:
    driver: bridge
