version: "3.8"
services:
    server:
      build:
        context: .
        dockerfile: ./packages/server/Dockerfile
      container_name: dendreth-api-server

    relayer:
      build:
        context: .
        dockerfile: ./packages/relayer/Dockerfile
      container_name: dendreth-relayer
